name: packer

on:
  push:
    branches:
      - main
      - dev

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build AMI
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run `packer init`
        id: init
        run: "packer init ./aws-ubuntu.pkr.hcl"

      # Explicitly define the variables in the workflow if needed
      - name: Set Variables
        run: |
          echo "INSTANCE_PROFILE_ID=YourInstanceProfileID" >> $GITHUB_ENV
          echo "BUCKET=YourBucketName" >> $GITHUB_ENV

      # New step to print variables
      - name: Print Variables
        run: |
          echo "IAM Instance Profile: $INSTANCE_PROFILE_ID"
          echo "S3 Bucket: $BUCKET"
          echo "AWS Access Key: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "Branch: ${{ github.ref_name }}"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./aws-ubuntu.pkr.hcl"

      - name: Run `packer build`
        id: build
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          INSTANCE_PROFILE_ID: $INSTANCE_PROFILE_ID
          BUCKET: $BUCKET
        run: "packer build -var 'iam_instance_profile=$INSTANCE_PROFILE_ID' -var 'bucket=$BUCKET' ./aws-ubuntu.pkr.hcl"
